### ISSUE TITLE
Confusing names 

### ISSUE THREAD

**Issue by Melisius** [peter-reinholdt/propertyfit#1]
Change the naming of:
 - methyl_charge
 - charge_methyl
 - neutral_methyl
 - methyl_neutral

Names should maybe just be one letter, "C", "c", "N" and "n", such that it matches the naming inside the parameterfile (the file with the charges and polarizabilities).

**Comment by peter-reinholdt** [comment]
I agree that the current system is confusing, but the CcNn is very clear.
I suggest we change all names, both in .constraints files and in parameter files to something along the lines of:
${SEQUENCE}_nterm=${NTERMSTATE}_cterm=${CTERMSTATE},
where SEQUENCE is something like VAL, NTERMSTATE is {charged, neutral or methyl} and CTERMSTATE is {charged, neutral or methyl}

**Comment by foeroyingur** [comment]
It is common practice to always start from the N-terminal. So in principle by using this you could use something like "nterm_AAA_cterm", where nterm can be charged, neutral, or acetyl, cterm can be charged, neutral, or nmethyl, and AAA is the three letter residue name. The methyl is misleading since it is not really just a methyl.
